# Exercises

In [1]:
# Import libraries 
import pandas as pd 
import numpy as np 
import os

In [2]:
# Create path 
path = r"C:\Users\Megan\Documents\CareerFoundry\Unit 4\InstaCart Python Project"

In [3]:
# Import merged dataframe  
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'products_orders_busy.pkl'))

In [4]:
# Create subset of the first 1000000 entries 
df = ords_prods_merge[:1000000]

In [5]:
df.head()

,order_id,user_id,order_number,order_day_of_week,order_hour,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,11.0,196,1,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders

In [6]:
# Group by product name 
df.groupby('product_name')

In [7]:
df.head()

,order_id,user_id,order_number,order_day_of_week,order_hour,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,11.0,196,1,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders

In [8]:
# Caluculate mean of order number column, grouped by department id column 
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [9]:
df.groupby('department_id').agg({'order_number': ['mean','min','max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

## Create a 'loyalty' flag for customers with a high amount of orders

In [10]:
# Split data into groups on user_id  
# Use transform on order_number to find max orders per user 
# Create column max_order 
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [11]:
ords_prods_merge.head(15)

,order_id,user_id,order_number,order_day_of_week,order_hour,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,11.0,196,1,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,22

In [12]:
pd.options.display.max_rows = None

In [13]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,order_day_of_week,order_hour,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,11.0,196,1,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,9
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,9
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,9
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,20
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,20
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,11
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,11
23,2497897,52,1,1,9,11.0,196,4,0,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,27
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,27
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,27
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,27
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,27
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,27
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,27
30,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,27
31,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,27
32,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,27
33,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,27
34,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,27
35,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,27
36,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,27
37,3205960,67,1,3,11,11.0,196,1,0,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,24
38,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,24
39,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,24
40,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,24
41,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,24
42,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,24
43,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,24
44,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,24
45,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,24
46,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,24
47,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,24
48,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,24
49,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,24
50,768572,67,16,4,10,9.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,24
51,150528,67,18,5,16,4.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,24
52,29758,67,19,0,14,9.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,24
53,1558976,67,21,1,9,5.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,24
54,863974,67,22,1,11,14.0,196,3,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,24
55,2308399,67,23,1,14,14.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,24
56,2759128,81,3,1,9,14.0,196,2,0,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,7
57,1812985,81,5,2,20,30.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,7
58,1889835,82,1,3,15,11.0,196,6,0,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,19
59,499460,82,3,5,10,5.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,19
60,2728456,82,4,0,11,16.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,19
61,2653743,82,6,4,9,13.0,196,5,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,19
62,1358880,82,9,1,10,30.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,19
63,343588,82,10,2,11,1.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,19
64,3034663,82,15,2,11,12.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,19
65,147262,82,18,1,13,7.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,19
66,3144004,82,19,2,15,8.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,19
67,2126069,98,3,0,9,25.0,196,7,0,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,14
68,2210120,98,7,5,14,5.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,14
69,681011,98,9,3,9,30.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,14
70,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,14
71,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,14
72,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,14
73,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,14
74,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,6
75,520620,120,1,3,11,11.0,196,2,0,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,3
76,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,3
77,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,6
78,2040988,195,1,1,14,11.0,196,2,0,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,58
79,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,58
80,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,58
81,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,58
82,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Most Orders,58
83,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,58
84,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,58
85,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,58
86,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,58
87,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,58
88,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,58
89,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,58
90,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,70
91,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,70
92,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,51
93,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,51
94,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,8
95,3226575,360,1,5,12,11.0,196,1,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Most Orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,Mid-Range Product,Regularly Busy,Average Orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,Mid-Range Product,Least Busy,Most Orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,Mid-Range Product,Busiest Days,Average Orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,Mid-Range Product,Least Busy,Average Orders,22

In [14]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal Customer'

In [15]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular Customer'

In [16]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New Customer'

In [17]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular Customer    15876776
Loyal Customer      10284093
New Customer         6243990
Name: loyalty_flag, dtype: int64

In [18]:
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New Customer             1
1         1      New Customer             2
2         1      New Customer             3
3         1      New Customer             4
4         1      New Customer             5
5         1      New Customer             6
6         1      New Customer             7
7         1      New Customer             8
8         1      New Customer             9
9         1      New Customer            10
10       15  Regular Customer            15
11       15  Regular Customer            17
12       15  Regular Customer            18
13       15  Regular Customer            21
14       15  Regular Customer            22
15       19      New Customer             2
16       19      New Customer             5
17       19      New Customer             7
18       21  Regular Customer            10
19       31  Regular Customer            10
20       31  Regular Customer            17
21       43  Regular Customer             6
22       43  Regular Customer             9
23       52  Regular Customer             1
24       52  Regular Customer             2
25       52  Regular Customer             3
26       52  Regular Customer             5
27       52  Regular Customer             7
28       52  Regular Customer             9
29       52  Regular Customer            10
30       52  Regular Customer            11
31       52  Regular Customer            12
32       52  Regular Customer            15
33       52  Regular Customer            17
34       52  Regular Customer            18
35       52  Regular Customer            19
36       52  Regular Customer            21
37       67  Regular Customer             1
38       67  Regular Customer             2
39       67  Regular Customer             3
40       67  Regular Customer             4
41       67  Regular Customer             5
42       67  Regular Customer             6
43       67  Regular Customer             8
44       67  Regular Customer             9
45       67  Regular Customer            10
46       67  Regular Customer            11
47       67  Regular Customer            12
48       67  Regular Customer            13
49       67  Regular Customer            14
50       67  Regular Customer            16
51       67  Regular Customer            18
52       67  Regular Customer            19
53       67  Regular Customer            21
54       67  Regular Customer            22
55       67  Regular Customer            23
56       81      New Customer             3
57       81      New Customer             5
58       82  Regular Customer             1
59       82  Regular Customer             3

In [19]:
# Export dataframe to pickle 
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'merge_loyalty.pkl'))